"""
Pytest configuration for visible tests.
Loads variant configuration if available.
"""
import json
import pytest
from pathlib import Path


def load_variant_config():
    """Load variant configuration from variant.json."""
    # Try .variant_config.json first (generated by workflow), then variant.json
    config_paths = [
        Path(__file__).parent.parent.parent / ".variant_config.json",
        Path(__file__).parent.parent.parent / "variant.json"
    ]

    for config_path in config_paths:
        if config_path.exists():
            with open(config_path) as f:
                return json.load(f)

    # Return default values if no variant config exists (template repo)
    return {
        "student_id": "template",
        "seed": 0,
        "required_functions": ["sqrt", "abs", "sin", "cos"],
        "test_constants": [25.0, 50.0, 75.0],
        "precision": 5
    }


@pytest.fixture(scope="session")
def variant_config():
    """Fixture providing variant configuration."""
    return load_variant_config()


@pytest.fixture
def student_id(variant_config):
    """Fixture providing student ID."""
    return variant_config["student_id"]


@pytest.fixture
def required_functions(variant_config):
    """Fixture providing required functions list."""
    return variant_config["required_functions"]


@pytest.fixture
def test_constants(variant_config):
    """Fixture providing test constants."""
    return variant_config["test_constants"]


@pytest.fixture
def precision(variant_config):
    """Fixture providing precision (decimal places)."""
    return variant_config["precision"]


@pytest.fixture
def tolerance(variant_config):
    """Fixture providing tolerance for floating point comparisons."""
    precision = variant_config["precision"]
    return 10 ** (-precision)
